create table `stats`(
	`id` bigint auto_increment primary key,
	`operating_mode` varchar(255),
	`hw_restricted` varchar(255),
	`current` int,
	`current_network` varchar(10),
	`rssi` int,
	`rssi_network` varchar(10),
	`ecio` int,
	`ecio_network` varchar(10),
	`io` int,
	`sinr` int,
	`rsrq` int,
	`rsrq_network` varchar(10),
	`snr` int,
	`snr_network` varchar(10),
	`rsrp` int,
	`rsrp_network` varchar(10),
	`mcc` int,
	`mnc` int,
	`network_description` varchar(255)
);
