name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.15

    - name: Build & Install
      run: | 
        sudo apt-get update && sudo apt-get install -y gpsd
        make install
        make uninstall
